<?xml version="1.0" encoding="utf-8"?><Database Name="SF1725021186" Class="SFDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PC45912\SQLEXPRESS;Initial Catalog=SF1725021186;Integrated Security=True" SettingsObjectName="SFBulkApiMain.Properties.Settings" SettingsPropertyName="SF1725021186ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="Id" Type="System.String" DbType="VarChar(18) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MasterRecordId" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="RecordTypeId" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BillingStreet" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BillingCity" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BillingState" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BillingPostalCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BillingCountry" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BillingLatitude" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="BillingLongitude" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="BillingGeocodeAccuracy" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BillingAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ShippingStreet" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ShippingCity" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ShippingState" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ShippingPostalCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ShippingCountry" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ShippingLatitude" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ShippingLongitude" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ShippingGeocodeAccuracy" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ShippingAddress" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PhotoUrl" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Industry" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="AnnualRevenue" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NumberOfEmployees" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="OwnerId" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedById" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedById" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SystemModstamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LastViewedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastReferencedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="JigsawCompanyId" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StandardAnschrift_Kranken__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BEGVTNR__c" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BEST_BEITR_GES__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="BS__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ENDVTNR__c" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GEBU_BEITR_GES__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Anzahl_Mitarbeiter_des_Maklers__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Gesamtumsatz_pro_Jahr__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="StandardAnschrift_Leben__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StandardAnschrift_Sach__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="INSPNR__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Jahresumsatz_Schwellenwert_erreicht__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MSN12__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NEU_BEITR_GES__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="StandardKommunikationsdaten_Kranken__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SCHADEN_AUFW_GES__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="STO_BEITR_MAK_GES__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SVTNR__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Umsatz_Makler_Gesamt_pro_Jahr__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Schwerpunkte__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="VTNR__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="umsatzplan_01__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Revers_Kranken__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Revers_Leben__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Revers_Sach__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Aktive_VTNR_mit_Kranken_Revers__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Aktive_VTNR_mit_Leben_Revers__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Aktive_VTNR_mit_Sach_Revers__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Anzahl_VTNR_in_der_Maklerakte__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Automatisch_erstellt__c" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Typ__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StandardKommunikationsdaten_Leben__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="StandardKommunikationsdaten_Sach__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="C1_B_Nr_Varianten__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="C1_Leben_Gesamtbewertung__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="C1_Leben_Stornoquote__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="C1_Stellenarten__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Email__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MSN_Praefix__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Mobil__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="V_KAT__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Zuordnungsregel__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Aufgabe_Jahresgespr_ch_Kranken__c" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Aufgabe_Jahresgespr_ch_Leben__c" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Aufgabe_Jahresgespr_ch_Sach__c" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Beliebige_Vermittlernummer__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Federf_hrer_Kranken__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Federf_hrer_Leben__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Federf_hrer_Sach__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MSN06__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Federf_hrer_1__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="VTNR_Verkn_pfungen__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Jahr_der_Hochstufung__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Kategorie__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Makkat__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Segment__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Sparten_Wertigkeit_Kranken__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Sparten_Wertigkeit_Leben__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Sparten_Wertigkeit_Sach__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Second_Federf_hrer_Sach__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Begruendung_fuer_Wertigkeit_Kranken__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Begruendung_fuer_Wertigkeit_Leben__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Second_Federfuehrer_Kranken__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Second_Federfuehrer_Leben__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Federf_hrer_2__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="VTNR_mit_B_Sperre_Leben_Kranken__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="VTNR_mit_B_Sperre_Sach__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="VTNR_mit_NG_Sperre__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="X1_Accountverantw_Federf_hrer_Kranken__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="X1_Accountverantw_Federf_hrer_Leben__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="X1_Accountverantw_Federf_hrer_Sach__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Ampelbild__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="C1_Ampelstatus__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MSN06_zu_Standortsicht__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MSN12_zu_Standortsicht__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Standortbetreuung__c" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Standort_Berlin__c" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Standort_Frankfurt__c" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Standort_Hamburg__c" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Standort_Koeln__c" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Standort_Leipzig__c" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Standort_Muenchen__c" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Standort_Stuttgart__c" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Poolbetreuung_MSN06__c" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Anzahl_Wichtige_Notizen__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Sach_Wichtige_Notiz_1__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Sach_Wichtige_Notiz_2__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Sach_Wichtige_Notiz_3__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Sach_Wichtige_Notiz_4__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Sach_Wichtige_Notiz_5__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Test_Multipicklist__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Anzahl_VTNR_in_der_Maklerakte_Number__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Maklerkategorie__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Sach_Fachlicher_Schwerpunkt__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Sach_Mitbewerbername__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Sach_Strategie_Zielgruppe__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Maklerverknuepfung__c" Member="Maklerverknuepfung__cs">
    <Type Name="Maklerverknuepfung__c">
      <Column Name="Id" Type="System.String" DbType="VarChar(18) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="RecordTypeId" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedById" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedById" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SystemModstamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastViewedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastReferencedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Vermittler__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Maklerakte__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomID__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZDF_Aggregation__c" Member="ZDF_Aggregation__cs">
    <Type Name="ZDF_Aggregation__c">
      <Column Name="Id" Type="System.String" DbType="VarChar(18) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedById" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LastModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedById" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SystemModstamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Angebote_Annahmequote_Beitrag_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_Annahmequote_Beitrag_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_Annahmequote_St_cke_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_Annahmequote_St_cke_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_Gesamtbetrag_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_Gesamtbetrag_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_Gesamtst_cke_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_Gesamtst_cke_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_JBTR_Abg_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_JBTR_Abg_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_JBTR_Ang_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_JBTR_Ang_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_JBTR_Offen_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_JBTR_Offen_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_Z_Abg_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_Z_Abg_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_Z_Ang_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_Z_Ang_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_Z_Offen_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Angebote_Z_Offen_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="BGVG_VTNR_Relation__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BGVG_VTNR__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Branche__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MSN12__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Produktion_NMBTR_Abweichung__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Produktion_NMBTR_DEC_GJ2__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Produktion_NMBTR_DEC_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Produktion_NMBTR_YTD_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Produktion_NMBTR_YTD_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Produktion_Neustueck_Abweichung__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Produktion_Neustueck_DEC_GJ2__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Produktion_Neustueck_DEC_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Produktion_Neustueck_YTD_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Produktion_Neustueck_YTD_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Reihenfolge__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Sortierung__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Status__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Storno_Beitrag_Abweichung__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Beitrag_DEC_GJ2__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Beitrag_DEC_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Beitrag_Quote_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Beitrag_Quote_YTD_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Beitrag_Quote_YTD_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Beitrag_YTD_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Beitrag_YTD_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Stueck_Abweichung__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Stueck_DEC_GJ2__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Stueck_DEC_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Stueck_Quote_DEC_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Stueck_Quote_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Stueck_Quote_YTD_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Stueck_Quote_YTD_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Stueck_YTD_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Storno_Stueck_YTD_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Bestand_BBTR_Abweichung__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Bestand_BBTR_DEC_GJ2__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Bestand_BBTR_DEC_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Bestand_BBTR_YTD_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Bestand_BBTR_YTD_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Bestand_Bestandsstueck_Abweichung__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Bestand_Bestandsstueck_DEC_GJ2__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Bestand_Bestandsstueck_DEC_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Bestand_Bestandsstueck_YTD_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Bestand_Bestandsstueck_YTD_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="BAQ_SoW_Beitrag_YTD_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="BAQ_SoW_Beitrag_YTD_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="BAQ_SoW_Beitrag_Abweichung__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Courtage_GJ1__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Courtage_GJ2__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Courtage_YTD_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Courtage_YTD_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="VTNR_SPARTE__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomID__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Qualifier__c" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Verm_Storno_Beitrag_YTD_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Verm_Storno_Stueck_YTD_GJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Verm_Storno_Beitrag_YTD_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Verm_Storno_Stueck_YTD_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Verm_Storno_Beitrag_Dec_GJ2__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Verm_Storno_Stueck_DEC_GJ2__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Verm_Storno_Beitrag_DEC_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Verm_Storno_Stueck_DEC_VJ__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Verm_Storno_Beitrag_Abweichung__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Verm_Storno_Stueck_Abweichung__c" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>